<?php $paymentIcons = $this->getGooglepayPaymentIcon(); ?>
<?php if (count($paymentIcons) > 0): ?>
    <?php foreach ($paymentIcons as $paymentIcon): ?>
        <img class="reepay-payment-icon" src="<?php echo $this->getViewFileUrl('Radarsofthouse_Reepay::img/payment_icons/'.$paymentIcon.'.png'); ?>">
    <?php endforeach; ?>
<?php endif; ?>



<script type="text/javascript">
    require(['jquery','Reepay'],function($,Reepay){
        Reepay.isGooglePayAvailable().then(isAvailable => {
            if( !isAvailable ){
                console.log("Google pay is not available");
                if( $('.reepay-payment-method-googlepay').length > 0 ){
                    $('.reepay-payment-method-googlepay').remove();
                }
            }
        });
    });
</script>
