<?php $order = $block->getOrder(); ?>
<div class="reepay-payment">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="logo">
                    <img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>">
                </div>
                <div>
                    Transaction ID : <?php echo $this->getPaymentTransactionId(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

