<?php $order = $block->getOrder(); ?>

<div class="reepay-payment-layout">
	<div class="logo-wrapper">
    <img class="logo" src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>">
	</div>
	<div class="reepay-overlay">
		<div class="order-section">
        	<div class="order-info">
                <p><?php echo __('Order ID :'); ?> <?php  echo $order->getIncrementId(); ?></p>
				<p><?php echo __('Total :'); ?> <?php  echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($order->getTotalDue(), true, false); ?></p>
			</div>

			<div class="button pay-btn">
				<?php echo __('Pay'); ?>
			</div>
        </div>
	</div>
	
    <script type="text/javascript">

        require(['jquery','Reepay'],function($,Reepay){

            var rp = new Reepay.ModalCheckout("<?php echo $this->getPaymentTransactionId(); ?>");

            rp.addEventHandler(Reepay.Event.Accept, function(data) {
                data._isAjax = 1;
                if( (data.error == undefined || data.error == "error.session.INVOICE_ALREADY_PAID" || data.error == "invoice_already_settled" ) && data.invoice ){
                    $.ajax({
                        url: '<?php echo $this->getAcceptUrl(); ?>',
                        method: 'POST',
                        data: data,
                    }).done(function(data){
                        if( data.status == 'success' ){
                            window.location = data.redirect_url;
                        }
                    }).fail(function(err){
                        console.log('Ajax: error');
                        console.log(err);
                    });
                }
            });

            rp.addEventHandler(Reepay.Event.Error, function(data) {
                // log error
                data._isAjax = 1;
                $.ajax({
                    url: '<?php echo $this->getErrorUrl(); ?>',
                    method: 'POST',
                    data: data,
                }).done(function(data){
                    if( data.status == 'success' ){
                        window.location = data.redirect_url;
                    }
                }).fail(function(err){
                    console.log("Ajax error");
                    console.log(err);
                });
            });

            rp.addEventHandler(Reepay.Event.Cancel, function(data) {
                data._isAjax = 1;
                $.ajax({
                    url: '<?php echo $this->getCancelUrl(); ?>',
                    method: 'POST',
                    data: data,
                }).done(function(data){
                    if( data.status == 'success' ){
                        window.location = data.redirect_url;
                    }
                }).fail(function(err){
                    console.log("Ajax error");
                    console.log(err);
                });
            });

            rp.addEventHandler(Reepay.Event.Close, function(data) {
                // not do anything for overlay close
            });

            $(document).ready(function(){
                $(".pay-btn").click(function(){
                    rp.show('<?php echo $this->getPaymentTransactionId(); ?>');
                });
            });

           

        });

	</script>
	
</div>
