<?php $order = $block->getOrder(); ?>

<div class="reepay-payment-layout">
	<div class="logo-wrapper">
    <img class="logo" src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>">
	</div>
    <script type="text/javascript">
        require(['jquery','Reepay'],function($,Reepay){
            var rp = new Reepay.WindowCheckout('<?php echo $this->getPaymentTransactionId(); ?>');
        });
	</script>
</div>
