<?php $order = $block->getOrder(); ?>

<div class="reepay-payment-layout">
    <div class="logo-wrapper">
        <img class="logo" src="<?= $escaper->escapeUrl($block->getLogoSrc()); ?>"
            alt="<?= $escaper->escapeHtml($block->getLogoAlt()); ?>">
    </div>

    <div class="reepay-embedded">
        <div class="order-section">
            <div class="order-info">
                <p><?= $escaper->escapeHtml(__('Order ID :')); ?> <?= $escaper->escapeHtml($order->getIncrementId()); ?></p>
                <p><?= $escaper->escapeHtml(__('Total :')); ?> <?= $escaper->escapeHtml($order->formatPrice($order->getTotalDue())); ?></p>
            </div>
        </div>
        <div id="rp_container"></div>
    </div>

    <script>
        require(['jquery', 'Reepay'], function($, Reepay) {

            var rp = new Reepay.EmbeddedCheckout("<?= $escaper->escapeHtml($block->getPaymentTransactionId()); ?>",
                'rp_container');

            rp.addEventHandler(Reepay.Event.Accept, function(data) {
                data._isAjax = 1;
                if ((data.error == undefined ||
                        data.error == "error.session.INVOICE_ALREADY_PAID" ||
                        data.error == "invoice_already_settled") &&
                    data.invoice
                ) {
                    $.ajax({
                        url: '<?= $escaper->escapeUrl($block->getAcceptUrl()); ?>',
                        method: 'POST',
                        data: data,
                    }).done(function(data) {
                        if (data.status == 'success') {
                            window.location = data.redirect_url;
                        }
                    }).fail(function(err) {
                        console.log('Ajax: error');
                        console.log(err);
                    });
                }
            });

            rp.addEventHandler(Reepay.Event.Error, function(data) {
                // log error
                $.ajax({
                    url: '<?= $escaper->escapeUrl($block->getErrorUrl()); ?>',
                    method: 'POST',
                    data: data,
                }).done(function(data) {
                    if (data.status == 'success') {
                        window.location = data.redirect_url;
                    }
                }).fail(function(err) {
                    console.log("Ajax error");
                    console.log(err);
                });
            });

            rp.addEventHandler(Reepay.Event.Close, function(data) {
                // not do anything for overlay close
            });

        });
    </script>

</div>
