<?php $order = $block->getOrder(); ?>

<div class="reepay-payment-layout">
    <div class="logo-wrapper">
        <img class="logo" src="<?= $block->escapeUrl($block->getLogoSrc()); ?>" 
            alt="<?= $block->escapeHtml($block->getLogoAlt()); ?>">
    </div>
    <div class="reepay-overlay">
        <div class="order-section">
            <div class="order-info">
                <p><?= $block->escapeHtml(__('Order ID :')); ?> <?= $block->escapeHtml($order->getIncrementId()); ?></p>
                <p><?= $block->escapeHtml(__('Total :')); ?> 
                    <?= $block->escapeHtml($this->helper(\Magento\Framework\Pricing\Helper\Data::class)
                        ->currency($order->getTotalDue(), true, false));
                    ?>
                </p>
            </div>

            <div class="button pay-btn">
                <?= $block->escapeHtml(__('Pay')); ?>
            </div>
        </div>
    </div>

    <script>

        require(['jquery','Reepay'],function($,Reepay){

            var rp = new Reepay.ModalCheckout("<?= $block->escapeHtml($block->getPaymentTransactionId()); ?>");

            rp.addEventHandler(Reepay.Event.Accept, function(data) {
                data._isAjax = 1;
                if( ( data.error == undefined || 
                    data.error == "error.session.INVOICE_ALREADY_PAID" || 
                    data.error == "invoice_already_settled" ) && 
                    data.invoice 
                ){
                    $.ajax({
                        url: '<?= $block->escapeUrl($block->getAcceptUrl()); ?>',
                        method: 'POST',
                        data: data,
                    }).done(function(data){
                        if( data.status == 'success' ){
                            window.location = data.redirect_url;
                        }
                    }).fail(function(err){
                        console.log('Ajax: error');
                        console.log(err);
                    });
                }
            });

            rp.addEventHandler(Reepay.Event.Error, function(data) {
                // log error
                data._isAjax = 1;
                $.ajax({
                    url: '<?= $block->escapeUrl($block->getErrorUrl()); ?>',
                    method: 'POST',
                    data: data,
                }).done(function(data){
                    if( data.status == 'success' ){
                        window.location = data.redirect_url;
                    }
                }).fail(function(err){
                    console.log("Ajax error");
                    console.log(err);
                });
            });

            rp.addEventHandler(Reepay.Event.Cancel, function(data) {
                data._isAjax = 1;
                $.ajax({
                    url: '<?= $block->escapeUrl($block->getCancelUrl()); ?>',
                    method: 'POST',
                    data: data,
                }).done(function(data){
                    if( data.status == 'success' ){
                        window.location = data.redirect_url;
                    }
                }).fail(function(err){
                    console.log("Ajax error");
                    console.log(err);
                });
            });

            rp.addEventHandler(Reepay.Event.Close, function(data) {
                // not do anything for overlay close
            });

            $(document).ready(function(){
                $(".pay-btn").click(function(){
                    rp.show('<?= $block->escapeHtml($block->getPaymentTransactionId()); ?>');
                });
            });
        });

    </script>
    
</div>
