<?php
$order = $block->getOrder();
$priceCurrency = $block->getPriceCurrency();
?>

<div class="reepay-payment-layout">
    <div class="logo-wrapper">
        <img class="logo" src="<?= $escaper->escapeUrl($block->getLogoSrc()); ?>"
            alt="<?= $escaper->escapeHtml($block->getLogoAlt()); ?>">
    </div>
    <div class="reepay-overlay">
        <div class="order-section">
            <div class="order-info">
                <p><?= $escaper->escapeHtml(__('Order ID :')); ?> <?= $escaper->escapeHtml($order->getIncrementId()); ?></p>
                <p><?= $escaper->escapeHtml(__('Total :')); ?> <?= $escaper->escapeHtml($priceCurrency->convertAndFormat($order->getTotalDue(), false)); ?></p>
            </div>

            <div class="button pay-btn">
                <?= $escaper->escapeHtml(__('Pay')); ?>
            </div>
        </div>
    </div>

    <script>
        require(['jquery', 'Reepay'], function($, Reepay) {

            var rp = new Reepay.ModalCheckout("<?= $escaper->escapeHtml($block->getPaymentTransactionId()); ?>");

            rp.addEventHandler(Reepay.Event.Accept, function(data) {
                data._isAjax = 1;
                if ((data.error == undefined ||
                        data.error == "error.session.INVOICE_ALREADY_PAID" ||
                        data.error == "invoice_already_settled") &&
                    data.invoice
                ) {
                    $.ajax({
                        url: '<?= $escaper->escapeUrl($block->getAcceptUrl()); ?>',
                        method: 'POST',
                        data: data,
                    }).done(function(data) {
                        if (data.status == 'success') {
                            window.location = data.redirect_url;
                        }
                    }).fail(function(err) {
                        console.log('Ajax: error');
                        console.log(err);
                    });
                }
            });

            rp.addEventHandler(Reepay.Event.Error, function(data) {
                // log error
                data._isAjax = 1;
                $.ajax({
                    url: '<?= $escaper->escapeUrl($block->getErrorUrl()); ?>',
                    method: 'POST',
                    data: data,
                }).done(function(data) {
                    if (data.status == 'success') {
                        window.location = data.redirect_url;
                    }
                }).fail(function(err) {
                    console.log("Ajax error");
                    console.log(err);
                });
            });

            rp.addEventHandler(Reepay.Event.Cancel, function(data) {
                data._isAjax = 1;
                $.ajax({
                    url: '<?= $escaper->escapeUrl($block->getCancelUrl()); ?>',
                    method: 'POST',
                    data: data,
                }).done(function(data) {
                    if (data.status == 'success') {
                        window.location = data.redirect_url;
                    }
                }).fail(function(err) {
                    console.log("Ajax error");
                    console.log(err);
                });
            });

            rp.addEventHandler(Reepay.Event.Close, function(data) {
                // not do anything for overlay close
            });

            $(document).ready(function() {
                $(".pay-btn").click(function() {
                    rp.show('<?= $escaper->escapeHtml($block->getPaymentTransactionId()); ?>');
                });
            });
        });
    </script>

</div>