<?php $order = $block->getOrder(); ?>

<div class="reepay-payment-layout">
    <div class="logo-wrapper">
        <img class="logo" src="<?= $block->escapeUrl($block->getLogoSrc()); ?>" 
            alt="<?= $block->escapeHtml($block->getLogoAlt()); ?>">
    </div>
    <script>
        require(['jquery','Reepay'],function($,Reepay){
             var rp = new Reepay.WindowCheckout('<?= $block->escapeHtml($block->getPaymentTransactionId()); ?>');
        });
    </script>
</div>
